Dev
CruCentralCoast/CruFirebase pull request #14
Opened 2018-02-03 18:36 UTC by jnogle

Added initial access rules (Kyle--need to test--will open issue), added api endpoint to register user and corresponding function triggered to add this new user to database, and api endpoint to delete a user and corresponding function triggered to remove this user from the database

2018-02-11 23:15 UTC, fedorareis requested changes
Address my other comments and fix the indentation on the index file. The indentation seems to be all over the place.

2018-02-11 23:15 UTC, fedorareis commented on functions/index.js
> +	if(typeof password === 'undefined' || password.length === 0) {
Does the auth section not do its own password validation?

2018-02-11 23:15 UTC, fedorareis commented on functions/index.js
> +    if(password.length < 8 || password.length > 72) {
This should be moved to be right next to the other Password validation.

2018-02-11 23:15 UTC, fedorareis commented on functions/index.js
> +exports.removeUser = functions.auth.user().onDelete(event => {
I'm a little confused as to the purpose of this function and how it differs from the delete function above.

2018-02-12 02:07 UTC, jnogle commented
- Fixed indentation
- Moved password validation statements next to one another
- To answer your first question, no, the auth sdk methods to create users do not do any of their own password validation
- To the second question, firebase stores users in a user pool separate from any database. Our users will obviously be created in a user pool for authentication purposes, but also written to the database so we can store additional information that the user pool does not account for (you can only store username, password, phone, photo there). One of the delete functions I've written (the REST endpoint) deletes the user from the user pool, and the second one removes that user from the database (this is automatically triggered by the user being removed from the pool). You'll notice the same pattern for creating users/adding them to the database.

2018-02-12 02:13 UTC, fedorareis approved these changes

2018-02-12 02:13 UTC, merged