Dev
CruCentralCoast/CruFirebase pull request #17
Opened 2018-02-12 08:38 UTC by jnogle

Added first data validation rules for certain collections, along with tests I've been able to run locally with the npm package called 'firestore-security-tests'...hopefully you can use these tests as a reference to further test the security rules you wrote earlier too @fedorareis

2018-02-26 00:07 UTC, fedorareis requested changes
Respond to my comments on the rules file and you should be good to go. I'm going to trust that the test files work correctly and are good to go.

2018-02-26 00:07 UTC, fedorareis commented on firestore.rules
> +    match /users/{id} {
Is there a specific reason for changing it to id? If not then I prefer the more verbose name.

2018-02-26 00:07 UTC, fedorareis commented on firestore.rules
> +    match /communityGroups/{id} {
See the previous comment about id.

2018-02-26 00:07 UTC, fedorareis commented on firestore.rules
>        allow update: if isLeader();
You are going to need explicit rules here also. the update rules should be mostly the same as the write rules with the condition that the leader info can't be changed.

2018-02-26 05:26 UTC, jnogle commented
Sounds good, I will make those changes and I am also going to make a second commit with the rest of the validation, so there will be a little more to look over

2018-03-02 22:59 UTC, fedorareis requested changes
The last change is to apply the id rule from the previous review to all of the models. So in general terms `match /models/{id}` should be `match /models/{modelsId}`

2018-03-03 23:24 UTC, fedorareis approved these changes

2018-03-03 23:25 UTC, merged